# Generated by Django 3.0.3 on 2020-06-24 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.IntegerField(blank=True, null=True)),
                ('adminname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('institutiontype', models.CharField(max_length=50)),
                ('institutionname', models.CharField(max_length=50)),
                ('testallowed', models.BooleanField(blank=True, null=True)),
                ('noofuser', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
