# Generated by Django 3.0.3 on 2020-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='adminaddeddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
