# Generated by Django 3.0.3 on 2020-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_adminprofile_adminaddeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCounters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('counter', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
