# Generated by Django 3.0.3 on 2020-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_allcounters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='testallowed',
            field=models.CharField(blank=True, choices=[('medclg', 'Medical College'), ('pathological', 'Pathological Laboratories'), ('hospitals', 'Hospitals'), ('medpro', 'Medical Professionals'), ('sciclg', 'Science College'), ('schools', 'Schools'), ('rnd', 'R&D Institues'), ('agriculture', 'Agriculture'), ('veterinary', 'Veterinary'), ('industrial', 'Industrial')], max_length=50, null=True),
        ),
    ]
