# Generated by Django 3.0.3 on 2020-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200625_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='institutiontype',
            field=models.CharField(blank=True, choices=[('medclg', 'Medical College'), ('pathological', 'Pathological Laboratories'), ('hospitals', 'Hospitals'), ('medpro', 'Medical Professionals'), ('sciclg', 'Science College'), ('schools', 'Schools'), ('rnd', 'R&D Institues'), ('agriculture', 'Agriculture'), ('veterinary', 'Veterinary'), ('industrial', 'Industrial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='testallowed',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('slideimaging', 'Whole slide imaging'), ('Bloodsmear', 'Peripheral Blood Smear'), ('malaria', 'Malaria'), ('sperm', 'Sperm'), ('Urine', 'urine')], max_length=50, null=True),
        ),
    ]
