# Generated by Django 3.0.3 on 2020-06-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200625_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='adminid',
        ),
    ]
