# Generated by Django 3.0.3 on 2020-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_adminprofile_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
