# Generated by Django 3.0.3 on 2020-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_adminprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='password',
            field=models.CharField(default='password', max_length=32),
        ),
    ]
