# Generated by Django 3.0.3 on 2020-07-02 09:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200702_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='testallowed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('invoice', 'Invoice'), ('slideimaging', 'Whole slide imaging'), ('Bloodsmear', 'Peripheral Blood Smear'), ('malaria', 'Malaria'), ('sperm', 'Sperm'), ('Urine', 'urine')], default='choices', max_length=30),
        ),
    ]
